site_name: DynaFEHMtools
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate
nav:
  - Overview: index.md
  - FEHMtools: fehm.md
  - Injury Metrics: injurymetrics.md